version: '3.8'

services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_ENABLED=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRATIONS=false
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge