server:
  port: 8761
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}
    registerWithEureka: false
    fetchRegistry: false